# config.yml
# Configuration file for the Rol plugin

# Vampire settings
vampire:
  teleport:
    cooldown: 20 # Cooldown in seconds for the teleport ability
    distance: 5.0 # Teleport distance in blocks
    particleDensity: 0.5 # Density of redstone dust particles during teleport
  nightVision:
    enabled: true #Enables night vision when the player is a vampire and during the night
  regeneration:
    enabled: true #Enables regeneration when the player is a vampire and during the night
  strength:
    enabled: true #Enables strength when the player is a vampire and during the night
  maxHealth: 40 # Maximum health (hearts) for vampires

# Night Creature settings
nightcreature:
  fireball:
    cooldown: 20 # Cooldown in seconds for the fireball ability
  nightVision:
    enabled: true #Enables night vision when the player is a night creature and during the night
  strength:
    enabled: true #Enables strength when the player is a night creature and during the night
  maxHealth: 30 # Maximum health (hearts) for night creatures
