vampire:
  teleport:
    cooldown: 20
    distance: 5.0
    particleDensity: 0.5
    particleCount: 20
  nightVision:
    enabled: true
    amplifier: 1
  regeneration:
    enabled: true
    amplifier: 2
  strength:
    enabled: true
    amplifier: 7
  maxHealth: 80

nightcreature:
  fireball:
    cooldown: 15
  nightVision:
    enabled: true
    amplifier: 1
  strength:
    enabled: true
    amplifier: 9
  maxHealth: 60

effect-tick-interval: 40
