name: Rol
version: 0
main: com.github.rol.Rol
description: Roleplaying plugin for Minecraft servers!
author: magenta555
website: https://github.com/magenta555/rol
api-version: 1.21.4
commands:
  rol:
    description: Display plugin information or use all Rol commands!
    permission: rol.rol
    permission-message: §d[Rol] You do not have permission to use this command.
    usage: /rol <species|class|etc.> # Added a placeholder for subcommands
  setspecies:
    description: Set a player's species.
    permission: rol.setspecies
    permission-message: §d[Rol] You do not have permission to use this command.
    usage: /rol setspecies <species> <player>
permissions:
  rol.rol:
    description: Allows the player to use the base /rol command and access subcommands.
    default: op
    children:
      rol.species: true # Grant rol.species if rol.rol is granted
  rol.setspecies:
    description: Allows the player to use the /rol setspecies command.
    default: op
