name: Rol
version: 0
main: com.github.rol.Rol
api-version: 1.21.4
author: magenta555
website: github.com/magenta555/rol
commands:
  species:
    description: Opens the species menu.
    usage: /species
    permission: rol.species
    permission-message: You need the permission rol.species!
  setspecies:
    description: Sets a player's species.
    usage: /setspecies <species> <player>
    permission: rol.setspecies
    permission-message: You need the permission rol.setspecies!
permissions:
  rol.species:
    description: Allows players to use the /species command
    default: true
  rol.setspecies:
    description: Allows players to use the /setspecies command
    default: op