name: Rol
version: 0
main: com.github.rol.Rol
api-version: 1.21.4
author: magenta555
website: github.com/magenta555/rol
commands:
  species:
    description: Opens the species menu.
    usage: /species
    permission: rol.species
  setspecies:
    description: Sets a player's specie.
    usage: /setspecies <species> <player>
    permission: rol.setspecies
  clearspecies:
    description: Clears a player's specie.
    usage: /clearspecies <player>
    permission: rol.clearspecies
  listspecies:
    description: List the species of all players or a single player.
    usage: /listspecies <player>
    permission: rol.listspecies
permissions:
  rol.species:
    description: Allows players to use the /species command
    default: true
  rol.setspecies:
    description: Allows players to use the /setspecies command
    default: op
  rol.clearspecies:
    description: Allows players to use the /clearspecies command
    default: op
  rol.listspecies:
    description: Allows players to use the /setspecies command
    default: true
